name: Deploy ASP.NET API

on:
  workflow_dispatch:   # ✅ enables Run workflow button
  push:
    branches:
      - main
    paths:
      - 'HamroKhata.API/**'

jobs:
  build-and-deploy:
    runs-on: windows-latest

    defaults:
      run:
        working-directory: HamroKhata.API

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - run: dotnet restore
      - run: dotnet build --configuration Release --no-restore
      - run: dotnet publish -c Release -o publish

      - uses: azure/webapps-deploy@v3
        with:
          app-name: HamroKhata-api
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: ./HamroKhata.API/publish